package:
  name: prometheus-node-exporter-1.5
  version: 1.5.0
  epoch: 1
  description: Prometheus Exporter for machine metrics
  copyright:
    - license: Apache-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - ca-certificates-bundle
      - busybox
      - bash
      - build-base
      - go
      - curl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/node_exporter
      tag: v${{package.version}}
      expected-commit: 1b48970ffcf5630534fb00bb0687d73c66d1c959

  - runs: |
      # Mitigate GHSA-vvpx-j8f3-3w6h
      go get golang.org/x/net@v0.7.0

      go mod tidy

      make build

  - runs: |
      install -Dm755 node_exporter "${{targets.destdir}}"/usr/bin/node_exporter

  - uses: strip

subpackages:
  - name: "prometheus-node-exporter-1.5-compat"
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          # The helm chart expects the node_exporter binaries to be in /bin instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"/bin
          ln -sf /usr/bin/node_exporter ${{targets.subpkgdir}}/bin/node_exporter
      - uses: strip

update:
  enabled: false
