name: Wolfictl Lint Docs

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.yaml"
      - "*.env"
      - "Makefile"
      - ".github/workflows/dag-push-enterprise.yaml"

      - "sub-os-openssl1/*.yaml"
      - "sub-os-openssl1/*.env"
      - "sub-os-openssl1/Makefile"
      - ".github/workflows/dag-push-enterprise-os-openssl1.yaml"

jobs:
  lint:
    name: Wolfictl Lint
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No lint required"'
